/** Real Chromium renderer check; native process/keyring checks belong to desktop smoke tests. */
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';
import { createServer } from 'vite';

const directory = 'test-artifacts/ui';
await mkdir(directory,{ recursive:true });
const server = await createServer({ server:{ host:'127.0.0.1',port:5174,strictPort:true } });
await server.listen();
let browser;
try {
  browser = await chromium.launch();
  const page = await browser.newPage({ viewport:{ width:1440,height:1000 },reducedMotion:'reduce' });
  const errors=[];
  page.on('pageerror',(error) => errors.push(error.message));
  await page.goto('http://127.0.0.1:5174/tests/visual/index.html');
  await page.getByRole('heading',{ name:'EXAMPLE-101',exact:true }).waitFor();
  await page.getByLabel('Colour theme').selectOption('light');
  await page.screenshot({ path:directory+'/overview-light.png',fullPage:true });
  assert.equal(await page.getByRole('button',{ name:'Approve and continue' }).count(),0);
  await page.getByRole('tab',{ name:'Overview',exact:true }).focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('tab',{ name:'Evidence',exact:true }).getAttribute('aria-selected'),'true');
  await page.getByRole('button',{ name:'evidence/verify.log',exact:true }).first().click();
  await page.getByText('Ran 2 tests in 0.280s',{ exact:false }).waitFor();
  await page.screenshot({ path:directory+'/evidence-light.png',fullPage:true });
  await page.getByRole('tab',{ name:'Diff',exact:true }).click();
  await page.getByText('src/api.py',{ exact:false }).first().waitFor();
  await page.getByLabel('Colour theme').selectOption('dark');
  await page.screenshot({ path:directory+'/diff-dark.png',fullPage:true });
  const opener=page.getByRole('button',{ name:/^Commands/ });
  await opener.click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');
  assert.equal(await opener.evaluate((element) => document.activeElement===element),true);
  await page.getByRole('tab',{ name:'Overview',exact:true }).click();
  await page.getByRole('button',{ name:/EXAMPLE-102/ }).click();
  await page.getByRole('heading',{ name:'Before Green Code' }).waitFor();
  await page.getByText('src',{ exact:true }).waitFor();
  await page.getByText('None · Docker containers',{ exact:true }).waitFor();
  await page.getByRole('button',{ name:'Approve and continue',exact:true }).waitFor();
  await page.screenshot({ path:directory+'/checkpoint-dark.png',fullPage:true });
  await page.setViewportSize({ width:760,height:1000 });
  await page.screenshot({ path:directory+'/checkpoint-narrow.png',fullPage:true });
  await page.setViewportSize({ width:1440,height:1000 });
  await page.goto('http://127.0.0.1:5174/tests/visual/index.html?screen=empty');
  await page.getByRole('heading',{ name:'Every change has a trace.' }).waitFor();
  await page.screenshot({ path:directory+'/cockpit-empty-dark.png',fullPage:true });
  await page.getByRole('button',{ name:'Setup & guides',exact:true }).click();
  await page.getByRole('heading',{ name:'Your tools. Your workflow.' }).waitFor();
  await page.getByLabel('Colour theme').selectOption('light');
  await page.screenshot({ path:directory+'/configuration-light.png',fullPage:true });
  const setup = page.getByRole('button',{ name:'Set up Copilot or Claude' });
  assert.ok(parseFloat(await setup.evaluate((node) => getComputedStyle(node).borderRadius)) >= 7);
  await setup.click();
  const copilot = page.getByRole('region',{ name:'GitHub Copilot' });
  await copilot.getByText('Installed',{ exact:true }).waitFor();
  await copilot.getByRole('button',{ name:'Test GitHub Copilot connection' }).click();
  await page.getByText('Synthetic connection succeeded.').waitFor();
  await page.getByLabel('Colour theme').selectOption('dark');
  await page.screenshot({ path:directory+'/runtimes-dark.png',fullPage:true });
  await page.getByRole('button',{ name:/Models & providers Governed role routing/ }).click();
  await page.getByRole('heading',{ name:'Connect your first provider' }).waitFor();
  await page.screenshot({ path:directory+'/providers-dark.png',fullPage:true });
  await page.getByRole('button',{ name:'Ollama',exact:true }).click();
  await page.getByLabel('API base URL',{ exact:false }).waitFor();
  await page.screenshot({ path:directory+'/provider-form-dark.png',fullPage:true });
  await page.getByRole('button',{ name:/Project facts Context for your team/ }).click();
  await page.getByLabel('Colour theme').selectOption('light');
  await page.screenshot({ path:directory+'/project-facts-light.png',fullPage:true });
  await page.getByRole('button',{ name:/Quickstart guides From setup to first result/ }).click();
  await page.setViewportSize({ width:390,height:844 });
  assert.equal(await page.getByLabel('Configuration page',{ exact:true }).inputValue(),'guides');
  assert.equal(await page.getByRole('navigation',{ name:'Configuration pages' }).count(),0);
  await page.screenshot({ path:directory+'/quickstart-mobile.png',fullPage:true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  await page.getByLabel('Configuration page',{ exact:true }).selectOption('runtimes');
  assert.equal(await page.getByLabel('Configuration page',{ exact:true }).inputValue(),'runtimes');
  await page.screenshot({ path:directory+'/runtimes-mobile.png',fullPage:true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  const previousUrl = page.url();
  await page.getByRole('button',{ name:'Open Connections' }).click();
  await page.getByRole('heading',{ name:'Connections',exact:true }).waitFor();
  assert.equal(page.url(),previousUrl);
  assert.equal(page.context().pages().length,1);
  assert.equal(await page.getByRole('heading',{ name:'Connect your coding assistant' }).isVisible(),false);
  await page.getByLabel('Proxy mode',{ exact:true }).selectOption('manual');
  await page.getByLabel('HTTP proxy',{ exact:true }).fill('http://proxy.example:8080');
  await page.getByRole('button',{ name:'Save network settings' }).click();
  await page.getByRole('status').filter({ hasText:'Network and proxy settings saved.' }).waitFor();
  await page.screenshot({ path:directory+'/connections-mobile-light.png',fullPage:true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  await page.setViewportSize({ width:1440,height:1000 });
  await page.getByRole('combobox',{ name:'Colour theme' }).selectOption('dark');
  await page.screenshot({ path:directory+'/connections-dark.png',fullPage:true });
  await page.getByRole('button',{ name:/Back to previous page/ }).click();
  await page.getByRole('heading',{ name:'Connect your coding assistant' }).waitFor();
  assert.equal(await page.getByRole('combobox',{ name:'Colour theme' }).inputValue(),'dark');
  await page.getByRole('button',{ name:'Open Connections' }).click();
  assert.equal(await page.getByLabel('HTTP proxy',{ exact:true }).inputValue(),'http://proxy.example:8080');
  await page.getByRole('combobox',{ name:'Colour theme' }).selectOption('light');
  await page.screenshot({ path:directory+'/connections-light.png',fullPage:true });
  await page.getByRole('button',{ name:/Back to previous page/ }).click();
  assert.equal(await page.getByRole('combobox',{ name:'Colour theme' }).inputValue(),'light');
  assert.deepEqual(errors,[]);
  console.log('Chromium cockpit, configuration and in-app Connections checks passed; screenshots saved.');
} finally {
  await browser?.close();await server.close();
}
