export const IPC_CHANNELS = {
  getSystemInfo: 'system:get-info',
  getSettings: 'settings:get',
  listPipelines: 'catalog:list-pipelines',
  installPipelinePack: 'catalog:install-pipeline-pack',
  listRuntimes: 'catalog:list-runtimes',
  configureRuntimeExecutable: 'settings:configure-runtime-executable',
  clearRuntimeExecutable: 'settings:clear-runtime-executable',
  selectProjectDirectory: 'projects:select-directory',
  selectAgentLibraryDirectory: 'agents:select-library',
  discoverAgents: 'agents:discover',
  prepareAgentExecution: 'agents:prepare-execution',
  createRunDraft: 'runs:create-draft',
  startPreviewRun: 'runs:start-preview',
  getPreviewRun: 'runs:get-preview',
  cancelPreviewRun: 'runs:cancel-preview',
  prepareExecution: 'runs:prepare-execution',
  approveAndStartExecution: 'runs:approve-start-execution',
  getExecutionRun: 'runs:get-execution',
  cancelExecution: 'runs:cancel-execution',
  runEvent: 'runs:event',
  openPath: 'shell:open-path'
} as const;
