import { contextBridge, ipcRenderer } from 'electron';
import type {
  AgentExecutionRequest,
  ConnectionId,
  CreateRunDraftRequest,
  DesktopApi,
  ProcessRuntimeId,
  ReplyToAgentExecutionRequest,
  RunEvent,
  RunEventListener,
  SaveConnectionRequest,
  SaveNetworkSettingsRequest
} from '../shared/contracts';

// Sandboxed Electron preload scripts only receive a restricted require() implementation.
// Keep runtime values in this file so the emitted preload has no local module dependency.
// Type-only imports above are erased by TypeScript.
const IPC_CHANNELS = {
  selectProjectProfile: 'configuration:select-project-profile',
  getForgeSetup: 'forge:setup',
  configureForgeHost: 'forge:configure-host',
  selectForgeInputs: 'forge:select-inputs',
  doctorForgeHost: 'forge:doctor',
  prepareForgeRun: 'forge:prepare',
  forgeAction: 'forge:action',
  listForgeRuns: 'forge:list',
  importForgeBundle: 'forge:import',
  getForgeRun: 'forge:get',
  getForgeEvents: 'forge:events',
  getForgeArtifact: 'forge:artifact',
  listModelConfiguration: 'models:list',
  saveModelProvider: 'models:save-provider',
  saveModelProfile: 'models:save-profile',
  removeModelConfiguration: 'models:remove',
  discoverProviderModels: 'models:discover',
  probeProviderModel: 'models:probe',
  cancelProviderProbe: 'models:cancel-probe',
  selectModelConfiguration: 'models:select-import',
  importModelConfiguration: 'models:import',
  exportModelConfiguration: 'models:export',
  exportProjectProfile: 'configuration:export-project-profile',
  getSystemInfo: 'system:get-info',
  getSettings: 'settings:get',
  saveNetworkSettings: 'settings:save-network',
  selectNetworkCaCertificate: 'settings:select-network-ca-certificate',
  testRuntimeConnection: 'settings:test-runtime-connection',
  listPipelines: 'catalog:list-pipelines',
  installPipelinePack: 'catalog:install-pipeline-pack',
  listRuntimes: 'catalog:list-runtimes',
  configureRuntimeExecutable: 'settings:configure-runtime-executable',
  clearRuntimeExecutable: 'settings:clear-runtime-executable',
  listConnections: 'connections:list',
  saveConnection: 'connections:save',
  removeConnection: 'connections:remove',
  testConnection: 'connections:test',
  selectProjectDirectory: 'projects:select-directory',
  selectAgentLibrary: 'agents:select-library',
  createRunDraft: 'runs:create-draft',
  startPreviewRun: 'runs:start-preview',
  getPreviewRun: 'runs:get-preview',
  cancelPreviewRun: 'runs:cancel-preview',
  prepareExecution: 'runs:prepare-execution',
  approveAndStartExecution: 'runs:approve-start-execution',
  getExecutionRun: 'runs:get-execution',
  cancelExecution: 'runs:cancel-execution',
  prepareAgentExecution: 'agents:prepare-execution',
  approveAndStartAgentExecution: 'agents:approve-start-execution',
  replyToAgentExecution: 'agents:reply-execution',
  getAgentExecutionRun: 'agents:get-execution',
  getLatestAgentExecutionRun: 'agents:get-latest-execution',
  getAgentExecutionEvents: 'agents:get-execution-events',
  cancelAgentExecution: 'agents:cancel-execution',
  openAgentWorkbench: 'windows:open-agent-workbench',
  runEvent: 'runs:event',
  openPath: 'shell:open-path'
} as const;

const api: DesktopApi = {
  selectProjectProfile: () => ipcRenderer.invoke(IPC_CHANNELS.selectProjectProfile),
  getForgeSetup: () => ipcRenderer.invoke(IPC_CHANNELS.getForgeSetup),
  configureForgeHost: () => ipcRenderer.invoke(IPC_CHANNELS.configureForgeHost),
  selectForgeInputs: () => ipcRenderer.invoke(IPC_CHANNELS.selectForgeInputs),
  doctorForgeHost: () => ipcRenderer.invoke(IPC_CHANNELS.doctorForgeHost),
  prepareForgeRun: (request) => ipcRenderer.invoke(IPC_CHANNELS.prepareForgeRun, request),
  forgeAction: (request) => ipcRenderer.invoke(IPC_CHANNELS.forgeAction, request),
  listForgeRuns: () => ipcRenderer.invoke(IPC_CHANNELS.listForgeRuns),
  importForgeBundle: () => ipcRenderer.invoke(IPC_CHANNELS.importForgeBundle),
  getForgeRun: (id) => ipcRenderer.invoke(IPC_CHANNELS.getForgeRun, id),
  getForgeEvents: (request) => ipcRenderer.invoke(IPC_CHANNELS.getForgeEvents, request),
  getForgeArtifact: (request) => ipcRenderer.invoke(IPC_CHANNELS.getForgeArtifact, request),
  listModelConfiguration: () => ipcRenderer.invoke(IPC_CHANNELS.listModelConfiguration),
  saveModelProvider: (request) => ipcRenderer.invoke(IPC_CHANNELS.saveModelProvider, request),
  saveModelProfile: (request) => ipcRenderer.invoke(IPC_CHANNELS.saveModelProfile, request),
  removeModelConfiguration: (request) => ipcRenderer.invoke(IPC_CHANNELS.removeModelConfiguration, request),
  discoverProviderModels: (request) => ipcRenderer.invoke(IPC_CHANNELS.discoverProviderModels, request),
  probeProviderModel: (request) => ipcRenderer.invoke(IPC_CHANNELS.probeProviderModel, request),
  cancelProviderProbe: (request) => ipcRenderer.invoke(IPC_CHANNELS.cancelProviderProbe, request),
  selectModelConfiguration: () => ipcRenderer.invoke(IPC_CHANNELS.selectModelConfiguration),
  importModelConfiguration: (request) => ipcRenderer.invoke(IPC_CHANNELS.importModelConfiguration, request),
  exportModelConfiguration: (request) => ipcRenderer.invoke(IPC_CHANNELS.exportModelConfiguration, request),
  exportProjectProfile: (draft) => ipcRenderer.invoke(IPC_CHANNELS.exportProjectProfile, draft),
  getSystemInfo: () => ipcRenderer.invoke(IPC_CHANNELS.getSystemInfo),
  getSettings: () => ipcRenderer.invoke(IPC_CHANNELS.getSettings),
  saveNetworkSettings: (request: SaveNetworkSettingsRequest) => ipcRenderer.invoke(IPC_CHANNELS.saveNetworkSettings, request),
  selectNetworkCaCertificate: () => ipcRenderer.invoke(IPC_CHANNELS.selectNetworkCaCertificate),
  testRuntimeConnection: (runtimeId: ProcessRuntimeId) => ipcRenderer.invoke(IPC_CHANNELS.testRuntimeConnection, runtimeId),
  listPipelines: () => ipcRenderer.invoke(IPC_CHANNELS.listPipelines),
  installPipelinePack: () => ipcRenderer.invoke(IPC_CHANNELS.installPipelinePack),
  listRuntimes: () => ipcRenderer.invoke(IPC_CHANNELS.listRuntimes),
  configureRuntimeExecutable: (runtimeId: ProcessRuntimeId) => ipcRenderer.invoke(IPC_CHANNELS.configureRuntimeExecutable, runtimeId),
  clearRuntimeExecutable: (runtimeId: ProcessRuntimeId) => ipcRenderer.invoke(IPC_CHANNELS.clearRuntimeExecutable, runtimeId),
  selectProjectDirectory: () => ipcRenderer.invoke(IPC_CHANNELS.selectProjectDirectory),
  selectAgentLibrary: () => ipcRenderer.invoke(IPC_CHANNELS.selectAgentLibrary),
  listConnections: () => ipcRenderer.invoke(IPC_CHANNELS.listConnections),
  saveConnection: (request: SaveConnectionRequest) => ipcRenderer.invoke(IPC_CHANNELS.saveConnection, request),
  removeConnection: (connectionId: ConnectionId) => ipcRenderer.invoke(IPC_CHANNELS.removeConnection, connectionId),
  testConnection: (connectionId: ConnectionId) => ipcRenderer.invoke(IPC_CHANNELS.testConnection, connectionId),
  createRunDraft: (request: CreateRunDraftRequest) => ipcRenderer.invoke(IPC_CHANNELS.createRunDraft, request),
  startPreviewRun: (request: CreateRunDraftRequest) => ipcRenderer.invoke(IPC_CHANNELS.startPreviewRun, request),
  getPreviewRun: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.getPreviewRun, runId),
  cancelPreviewRun: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.cancelPreviewRun, runId),
  prepareExecution: (request: CreateRunDraftRequest) => ipcRenderer.invoke(IPC_CHANNELS.prepareExecution, request),
  approveAndStartExecution: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.approveAndStartExecution, runId),
  getExecutionRun: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.getExecutionRun, runId),
  cancelExecution: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.cancelExecution, runId),
  prepareAgentExecution: (request: AgentExecutionRequest) => ipcRenderer.invoke(IPC_CHANNELS.prepareAgentExecution, request),
  approveAndStartAgentExecution: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.approveAndStartAgentExecution, runId),
  replyToAgentExecution: (request: ReplyToAgentExecutionRequest) => ipcRenderer.invoke(IPC_CHANNELS.replyToAgentExecution, request),
  getAgentExecutionRun: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.getAgentExecutionRun, runId),
  getLatestAgentExecutionRun: () => ipcRenderer.invoke(IPC_CHANNELS.getLatestAgentExecutionRun),
  getAgentExecutionEvents: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.getAgentExecutionEvents, runId),
  cancelAgentExecution: (runId: string) => ipcRenderer.invoke(IPC_CHANNELS.cancelAgentExecution, runId),
  openAgentWorkbench: () => ipcRenderer.invoke(IPC_CHANNELS.openAgentWorkbench),
  onRunEvent: (listener: RunEventListener) => {
    const handler = (_event: Electron.IpcRendererEvent, runEvent: RunEvent) => listener(runEvent);
    ipcRenderer.on(IPC_CHANNELS.runEvent, handler);
    return () => ipcRenderer.removeListener(IPC_CHANNELS.runEvent, handler);
  },
  openPath: (targetPath: string) => ipcRenderer.invoke(IPC_CHANNELS.openPath, targetPath)
};

contextBridge.exposeInMainWorld('agentPipeline', Object.freeze(api));
